### Shuffle datasets for annotation

1. Collective action

In [1]:
import pandas as pd

file_path = '../data/annotation_set_action.csv'
data = pd.read_csv(file_path)

data.head()

,sentence,classification,annotator1,annotator2,annotator3,collectiveAction,category1
0,And they will do anything and everything to mi...,NaN,NaN,NaN,NaN,0,arts
1,Now what's unique about this is that the EPA i...,NaN,NaN,NaN,NaN,1,arts
2,But it was the basic premise of freedom on the...,NaN,NaN,NaN,NaN,0,arts
3,It's not relativistic.,NaN,NaN,NaN,NaN,1,arts
4,But even though some people feel that way that...,NaN,NaN,NaN,NaN,0,arts

In [2]:
shuffled_data = data.sample(frac=1).reset_index(drop=True)
shuffled_data.head()

,sentence,classification,annotator1,annotator2,annotator3,collectiveAction,category1
0,That's ultimately what it comes out to.,NaN,NaN,NaN,NaN,1,comedy
1,I think that both those things are wrong.,NaN,NaN,NaN,NaN,1,leisure
2,"And on average, that food goes from being a wa...",NaN,NaN,NaN,NaN,1,arts
3,It's not like the Exodus story of Egypt where ...,NaN,NaN,NaN,NaN,1,religion
4,"And then you have left, I guess, there's volun...",NaN,NaN,NaN,NaN,0,arts

In [3]:
shuffled_data.to_csv(file_path, index=False)

In [4]:
shuffled_data = shuffled_data.drop(columns=['classification', 'collectiveAction', 'category1'])
shuffled_data.to_csv(file_path, index=False)

2. Racial justice

In [15]:
import pandas as pd

file_path = '../data/annotation_set_race.csv'
data = pd.read_csv(file_path)

data.head()

,sentence,classification,annotator1,annotator2,annotator3,collectiveAction,racialJustice,category1
0,I think it's kind of symbiotic but it's a lot of it.,NaN,NaN,NaN,NaN,1,0,arts
1,"I suppose we should probably also say that as we're recording this, America is basically on fire with its own race issues.",NaN,NaN,NaN,NaN,1,1,arts
2,"And I don't want to be the one who's on social media being like, stop gender based violence and just being like, ooh, like at least I also did that.",NaN,NaN,NaN,NaN,0,0,arts
3,But even about this whole racism thing that just seems to keep on erupting my police brutality all these things I think we ought to pray.,NaN,NaN,NaN,NaN,0,1,arts
4,"I've now rectified that, but that kind of set me back for actually learning about new games to put into that vlog.",NaN,NaN,NaN,NaN,1,0,arts

In [16]:
shuffled_data = data.sample(frac=1).reset_index(drop=True)
shuffled_data.head()

,sentence,classification,annotator1,annotator2,annotator3,collectiveAction,racialJustice,category1
0,"And then lastly, the wild card for me, I'll put Kansas City down, mostly because Patrick Mahomes has been outspoken about the support in the Black Lives Matter movement.",NaN,NaN,NaN,NaN,1,1,sports
1,It's not reciprocated specifically from Black men.,NaN,NaN,NaN,NaN,1,1,leisure
2,I believe he just dropped the charges like last week or something like that.,NaN,NaN,NaN,NaN,1,0,society
3,But working out my salvation can't stop at consuming knowledge.,NaN,NaN,NaN,NaN,1,0,religion
4,"I personally chose the coral, but what I really like about it is they have a ton of different colors, black, white, pastel, neon.",NaN,NaN,NaN,NaN,1,0,health

In [17]:
shuffled_data.to_csv(file_path, index=False)

In [18]:
shuffled_data = shuffled_data.drop(columns=['classification', 'collectiveAction', 'racialJustice', 'category1'])
shuffled_data.to_csv(file_path, index=False)

### Label distributions

1. Collective action

In [1]:
import pandas as pd
import glob

dfs = []

for i in range(1, 11):
    files = glob.glob(f"../data/episodes/part_{i}/*.csv")  
    for file in files:
        df = pd.read_csv(file, usecols=["collectiveAction"])  
        dfs.append(df)

all_data = pd.concat(dfs, ignore_index=True)

category_counts = all_data["collectiveAction"].value_counts()

print(category_counts)

collectiveAction
1    1994423
0     527736
Name: count, dtype: int64

1.a. speaker turns version

In [83]:
import pandas as pd
import glob

dfs = []

files = glob.glob(f"../data/episodes/speaker_turns/*.csv")  
print(len(files))

for file in files:
    df = pd.read_csv(file, usecols=["collectiveAction"])  
    dfs.append(df)

all_data = pd.concat(dfs, ignore_index=True)

category_counts = all_data["collectiveAction"].value_counts()

print(category_counts)

10496

ValueError: Usecols do not match columns, columns expected but not found: ['collectiveAction']

2. Racial justice

In [9]:
import pandas as pd
import glob

dfs = []

for i in range(1, 11):
    files = glob.glob(f"../data/episodes/part_{i}/*.csv")  
    for file in files:
        df = pd.read_csv(file, usecols=["racialJustice"])  
        dfs.append(df)

all_data = pd.concat(dfs, ignore_index=True)

category_counts = all_data["racialJustice"].value_counts()

print(category_counts)

racialJustice
0    2408208
1     113951
Name: count, dtype: int64

2.a. speaker turns version

In [80]:
import pandas as pd
import glob

dfs = []

files = glob.glob(f"../data/episodes/speaker_turns/*.csv")  
print(len(files))

for file in files:
    df = pd.read_csv(file, usecols=["racialJustice"])  
    dfs.append(df)

all_data = pd.concat(dfs, ignore_index=True)

category_counts = all_data["racialJustice"].value_counts()

print(category_counts)

10496
racialJustice
0.0    559254
1.0     13875
Name: count, dtype: int64

3. Both racialJustice and collectiveAction

In [10]:
import pandas as pd
import glob

dfs = []

for i in range(1, 11):
    files = glob.glob(f"../data/episodes/part_{i}/*.csv")  
    for file in files:
        df = pd.read_csv(file, usecols=["collectiveAction", "racialJustice"])  
        dfs.append(df)

all_data = pd.concat(dfs, ignore_index=True)

# Count rows where both racialJustice and collectiveAction are 1
both_count = ((all_data["collectiveAction"] == 1) & (all_data["racialJustice"] == 1)).sum()

print(f"Count of rows where both collectiveAction and racialJustice are 1: {both_count}")

Count of rows where both collectiveAction and racialJustice are 1: 65988

3.a. speaker turns version

In [ ]:
import pandas as pd
import glob

dfs = []

files = glob.glob(f"../data/episodes/part_{i}/*.csv")  

for file in files:
    df = pd.read_csv(file, usecols=["collectiveAction", "racialJustice"])  
    dfs.append(df)

all_data = pd.concat(dfs, ignore_index=True)

# Count rows where both racialJustice and collectiveAction are 1
both_count = ((all_data["collectiveAction"] == 1) & (all_data["racialJustice"] == 1)).sum()

print(f"Count of rows where both collectiveAction and racialJustice are 1: {both_count}")

### Check rows marked as collective action re: racial justice

In [18]:
import pandas as pd
import glob

dfs = []

for i in range(1, 11):
    files = glob.glob(f"../data/episodes/part_{i}/*.csv")  
    for file in files:
        df = pd.read_csv(file)  
        dfs.append(df)

all_data = pd.concat(dfs, ignore_index=True)

filtered_data = all_data[(all_data["collectiveAction"] == 0) & (all_data["racialJustice"] == 1)]

# Save to CSV
filtered_data.to_csv("../data/sentences_to_study.csv", index=False)

print(f"Saved {len(filtered_data)} rows to 'sentences_to_study.csv'.")

Saved 47963 rows to 'sentences_to_study.csv'.

In [16]:
pd.set_option('display.max_colwidth', None)

In [21]:
sentences_to_study = pd.read_csv('../data/sentences_to_study.csv')
sentences_to_study.head(50)

,sentence,classification,annotator1,annotator2,annotator3,collectiveAction,racialJustice
0,"And I read up on history and black literature, African American literature, African literature, I read up on the struggle.",NaN,NaN,NaN,NaN,0,1
1,Like Al Sharpton.,NaN,NaN,NaN,NaN,0,1
2,I experienced racism and injustice and inequality.,NaN,NaN,NaN,NaN,0,1
3,"And as a black man, I feel that it's part of my obligation to the black community to participate and contribute in some form of fashion.",NaN,NaN,NaN,NaN,0,1
4,"During an interview with Fox News Wednesday night, Lieutenant Governor Dan Patrick said, ""Adressing racism in the country, a long-standing issue brought to the forefront again after the death of George Floyd in police custody last week, is an issue of love that can be resolved through loving God.""",NaN,NaN,NaN,NaN,0,1
5,"From the original crime that was committed by the police officer on George Floyd to what's happening in our streets, we have racism in this country.",NaN,NaN,NaN,NaN,0,1
6,"We need a culture change to address this racism.""",NaN,NaN,NaN,NaN,0,1
7,"The Lieutenant Governor said that the killing of Floyd, ""a black man who was filmed crying out for help as a white police officer, pinned him to the ground with a knee to his neck, was a crime against black America.""",NaN,NaN,NaN,NaN,0,1
8,"Ladies and gentlemen sorry about that right there but anyways to resume after whatever just happened right there like like like many other organizations and just people in general the UFC also has some people in their organization who are hurting from what's been going on in the world right now and pretty much everybody is at the moment because of the divide that's going on with not only the coronavirus that's going around but also the racial divide in the country right now with the death of George Floyd and UFC fighters Randy Brown, Israel Ada San, Adasanya, Michael Bizbing and Rose Namahunis voice their opinions and put out a video supporting the Black Lives Matter campaign saying that they want to they want us to stand with our brothers and sisters here on earth and join them in the fight for equality especially those who are fighting an uphill battle right now with the systemic racism that is obviously deep rooted in the United States obviously nobody today is responsible for the deep rooted systemic racism that's within the government and unfortunately police comes I know every day that we as humans almost every single human we want good things for other people so I know every day we long for change in those areas and we simply want equality because deep down every person is good people deserve second chances just like that song says I believe most people are good so everybody usually wants good for other people and it's good to see some UFC fighters even doing doing or posting things that other people are maybe too afraid or too shy to post that is promoting equality here in the United States and fighting the uphill battle against systemic racism I think that's all we have today though a little bit shorter than I would like I'm trying to do longer episodes I just I just miss miss miss estimate I guess how long these episodes are going to be but hopefully next week or the week after we can have a much longer one so thank you guys for tuning in with that I am Gunnar Gillette from National Sports Radio signing off I will catch you guys in the next episode thank you for tuning in.",NaN,NaN,NaN,NaN,0,1
9,We look at the civil rights movement and all that people of color have to go through to try to obtain this kind of equity and humanity.,NaN,NaN,NaN,NaN,0,1
10,And I think that there is there to live in our country and think that there's no systemic racism to think that there's not injustice is foolish.,NaN,NaN,NaN,NaN,0,1
11,So praying for you guys and we're praying for Black brothers and sisters and we're praying for Amad Aubrey's family and just the situation.,NaN,NaN,NaN,NaN,0,1
12,So I hope we can protest fairly and be protected for our First Amendment rights and stand in solidarity with George Floyd's family and demand fairness and openness and community policing and all the things that we believe in and fairness and employment and income and all the things that people have a right to protest for.,NaN,NaN,NaN,NaN,0,1
13,And we got to understand that this crosses all boundaries of race.,NaN,NaN,NaN,NaN,0,1
14,"I mean, you're not going to achieve justice for George Floyd or for African American people by tearing out an ATM in a bank or breaking all the windows out of a store or destroying across the country, black businesses in neighborhoods.",NaN,NaN,NaN,NaN,0,1
15,"Well, he stood for change and stood for racial equality.",NaN,NaN,NaN,NaN,0,1
16,"In the turbulent 1960s, young John Lewis stood side by side with Martin Luther King, Jr. and other civil rights crusaders displaying unwavering courage.",NaN,NaN,NaN,NaN,0,1
17,"Through years of continual nonviolent protests, John Lewis battled segregation head on and shined a spotlight on the cruelty of racism in America.",NaN,NaN,NaN,NaN,0,1
18,"In the fall of 1959, he started conducting these unbelievable training sessions, a small group of students, the calm, listen to him, go through role playing, we will help what we call social drama, because black people and white people couldn't be seated together in a theater.",NaN,NaN,NaN,NaN,0,1
19,"And so in 1961, John Lewis and other civil rights activists decided to get on a bus to challenge segregation in the racially divided South.",NaN,NaN,NaN,NaN,0,1
20,"The freedom ride came into being on the part of an organization called Core, the Congress of Racial Equality.",NaN,NaN,NaN,NaN,0,1
21,"So the National Guard took us to the Mississippi state line, and you get to Mississippi, the Mississippi state troopers, put us in jail, black and white freedom riders.",NaN,NaN,NaN,NaN,0,1
22,They did the same thing for the white and black women.,NaN,NaN,NaN,NaN,0,1
23,"But for many years, people of color could not register to vote, especially in the 11 states that all confederacy.",NaN,NaN,NaN,NaN,0,1
24,"Just to hold you the racial, unrepresented in outrage and collaboration in solidarity with Black Lives Matter and that movement and also in consciousness of COVID-19 and how we navigate this complex moment in time.",NaN,NaN,NaN,NaN,0,1
25,Black Lives Matter.,NaN,NaN,NaN,NaN,0,1
26,"I sit and ponder that all lives matter, not to take away from the BLM movement, but just a reminder to self and to others that Korean lives matter.",NaN,NaN,NaN,NaN,0,1
27,"And that is the issue of talking about and embracing the ability to talk about race, which quite frankly, not many people like to do.",NaN,NaN,NaN,NaN,0,1
28,"How do you wrap your arms around the dialogue about black, white discrimination and the all of the hot button topics that many people when they go back to work are certainly going to have to endure.",NaN,NaN,NaN,NaN,0,1
29,"They shut down 8,000 stores across the country two years ago in order to conduct racial bias education training after the nationwide protests that subsequently ensued over the treatment of the black customers.",NaN,NaN,NaN,NaN,0,1
30,"And that isn't the case for everyone, especially people of color, including black people.",NaN,NaN,NaN,NaN,0,1
31,And no more black people should be shot in order for us to demand justice.,NaN,NaN,NaN,NaN,0,1
32,"Okay, show them where it hurts, abstain from spending your money in their shops and economies and invest in Black owned businesses.",NaN,NaN,NaN,NaN,0,1
33,"I took it as though he was talking about racist, abstain from spending money in their economies as in racist.",NaN,NaN,NaN,NaN,0,1
34,"I think he's trying to stick up for the black community 'cause he's black himself, and he's trying to be, he's in a difficult situation because look, we've got sky television.",NaN,NaN,NaN,NaN,0,1
35,"So I don't believe in all this racism, like, and while you're on the subject, that fella that got his knee put on his neck in America, yeah, that is murder and that policeman murdered him, that's for sure.",NaN,NaN,NaN,NaN,0,1
36,"So that's having right, black and white, again, abused by the police anywhere in America, because it's there.",NaN,NaN,NaN,NaN,0,1
37,"I personally spoke from the heart about the Watford community, ideas of us personally investing seven figures to create unity and opportunities, and adding change to the African and Caribbean community.",NaN,NaN,NaN,NaN,0,1
38,"And actually I think that brings us really nicely onto the sort of secondary that I think is really important to talk about is diversity in STEM and what kind of responsibility we have to reach out to engage with and encourage people of different genders, races and especially kind of economic backgrounds and bring them into science and engineering.",NaN,NaN,NaN,NaN,0,1
39,That's why the black male is so in the United States of America is so heavily policed.,NaN,NaN,NaN,NaN,0,1
40,That's why the knee is kept in the necks of the black person.,NaN,NaN,NaN,NaN,0,1
41,"All over the world, everybody's marching everywhere, all of a sudden, and you know what, I was thinking, I saw all the celebrities like donating stuff and saying they're gonna give, who's saying they're gonna give 10 million to Black business citizens and stuff over the next 10 years, and I'm like why did it take this for you to do that?",NaN,NaN,NaN,NaN,0,1
42,"I think I've never heard of that being done either, but when I was scrolling Instagram on Blackout Tuesday, a lot of people were saying oh I'm going to support only black businesses today on Blackout Tuesday, and I was like oh my goodness, thank you so much for supporting us on this one day of the week out of the whole year, like come on, come on, I'm not falling for this, to me it's all a pretense of caring about what black people go through, because to me why did it take this long for all of this to happen, because people have been dying at the other hands of police from Blackout how long, right?",NaN,NaN,NaN,NaN,0,1
43,"Yeah, I understand people's rage in that for the police, they don't see the bad ones, let's say, they don't see black people as good of sending people.",NaN,NaN,NaN,NaN,0,1
44,"It's so ridiculous, but I don't think races are concerned about because a lot of black people, they have white people voice and they have their black people voice.",NaN,NaN,NaN,NaN,0,1
45,"My final thoughts on race is that you guys, like they need to see us as human beings.",NaN,NaN,NaN,NaN,0,1
46,And we need to free ourselves as Black people.,NaN,NaN,NaN,NaN,0,1
47,"If you're going to support Black people, support Black people.",NaN,NaN,NaN,NaN,0,1
48,"If you're going to support Black people, whatever the case may be.",NaN,NaN,NaN,NaN,0,1
49,"Currently, through the Black Lives Matter movement that is based off the hope that America will finally see black people equal to white.",NaN,NaN,NaN,NaN,0,1

In [22]:
episodes_with_id = pd.read_csv('../data/episodes_with_id.csv')

In [23]:
mp3url_episode_id = episodes_with_id[['mp3url', 'episode_id']]
mp3url_episode_id.head()

,mp3url,episode_id
0,https://anchor.fm/s/11abe148/podcast/play/15344549/https%3A%2F%2Fd3ctxlq1ktw2nl.cloudfront.net%2Fproduction%2F2020-5-17%2F83194249-44100-2-bc23c65d66c68.mp3,1
1,https://anchor.fm/s/14d9e07c/podcast/play/14562096/https%3A%2F%2Fd3ctxlq1ktw2nl.cloudfront.net%2Fstaging%2F2020-06-16%2F3c6085a195c08d5484171e1a6bfa36da.m4a,2
2,https://anchor.fm/s/e668dbd4/podcast/play/73891674/https%3A%2F%2Fd3ctxlq1ktw2nl.cloudfront.net%2Fstaging%2F2023-6-26%2F340773028-44100-1-ffe7374ac6b2bd72.mp3,3
3,https://anchor.fm/s/126c0978/podcast/play/15840996/https%3A%2F%2Fd3ctxlq1ktw2nl.cloudfront.net%2Fstaging%2F2020-07-21%2Fccb7a609626d52cfe97eebc50d050859.m4a,4
4,https://anchor.fm/s/126c0978/podcast/play/14603313/https%3A%2F%2Fd3ctxlq1ktw2nl.cloudfront.net%2Fproduction%2F2020-4-31%2F78406002-44100-2-57f2a88169a22.m4a,5

In [24]:
mp3url_episode_id.to_csv('../data/mp3url_episode_id.csv', index=False)

### Three sets of annotations

In [45]:
pd.set_option('display.max_colwidth', None)

1. Racial justice

In [85]:
import pandas as pd

# change the annotation file paths when received
file_paths = [
    '../data/annotation_set_race_davide.csv',
    '../data/annotation_set_race_arianna.csv',
    '../data/annotation_set_race_theodora.csv'
]
labels_path = '../data/annotation_set_race_labels.csv'

dfs = [pd.read_csv(file_path) for file_path in file_paths]
labels_df = pd.read_csv(labels_path)

# Identify the non-NaN columns for each annotator
annotator_columns = []
for df in dfs:
    for col in ['annotator1', 'annotator2', 'annotator3']:
        if df[col].notna().any():
            annotator_columns.append(df[col])
            break

# Add the 'note' column from Arianna's annotation set
arianna_notes = dfs[1]['note'] if 'note' in dfs[1].columns else None

# Create a new DataFrame with the sentence column and the three annotator columns
race_annotations = pd.DataFrame({
    'sentence': dfs[0]['sentence'],
    'davide': annotator_columns[0],
    'arianna': annotator_columns[1],
    'theodora': annotator_columns[2],
    'arianna_note': arianna_notes
})

# Function to compute majority vote
def majority_vote(row):
    return row.mode().iloc[0] if not row.mode().empty else None

# Apply majority vote function
race_annotations['majority'] = race_annotations[['davide', 'arianna', 'theodora']].apply(majority_vote, axis=1)

# Merge with racialJustice column from labels_df
race_annotations = race_annotations.merge(labels_df[['sentence', 'racialJustice']], on='sentence', how='left')

# Display the result
race_annotations.head()

,sentence,davide,arianna,theodora,arianna_note,majority,racialJustice
0,"And then lastly, the wild card for me, I'll put Kansas City down, mostly because Patrick Mahomes has been outspoken about the support in the Black Lives Matter movement.",1,1,1,mention of the movement,1,1
1,It's not reciprocated specifically from Black men.,1,1,1,NaN,1,1
2,I believe he just dropped the charges like last week or something like that.,0,0,0,NaN,0,0
3,But working out my salvation can't stop at consuming knowledge.,0,0,0,NaN,0,0
4,"I personally chose the coral, but what I really like about it is they have a ton of different colors, black, white, pastel, neon.",0,0,0,NaN,0,0

In [87]:
race_annotations[['sentence', 'majority']].to_csv('../data/annotation_set_race_majority.csv', index=False)

In [86]:
from sklearn.metrics import accuracy_score, confusion_matrix

# Compute accuracy
accuracy = accuracy_score(race_annotations['racialJustice'], race_annotations['majority'])

# Compute confusion matrix
tn, fp, fn, tp = confusion_matrix(race_annotations['racialJustice'], race_annotations['majority']).ravel()

# Print results
print(f'Accuracy: {accuracy:.4f}')
print(f'True Positives (TP): {tp}')
print(f'True Negatives (TN): {tn}')
print(f'False Positives (FP): {fp}')
print(f'False Negatives (FN): {fn}')

Accuracy: 0.9421
True Positives (TP): 87
True Negatives (TN): 92
False Positives (FP): 3
False Negatives (FN): 8

In [58]:
import krippendorff
import numpy as np

# Extract the relevant columns
data = race_annotations[['davide', 'arianna', 'theodora']].to_numpy()
data = np.transpose(data)

# Calculate Krippendorff's alpha
alpha = krippendorff.alpha(reliability_data=data, level_of_measurement='nominal')

print(f"Krippendorff's alpha: {alpha:.4f}")

Krippendorff's alpha: 0.8664

2. Collective action

In [88]:
import pandas as pd

# change the annotation file paths when received
file_paths = [
    '../data/annotation_set_action_davide.csv',
    '../data/annotation_set_action_arianna.csv',
    '../data/annotation_set_action_theodora.csv'
]
labels_path = '../data/annotation_set_action_labels.csv'

dfs = [pd.read_csv(file_path) for file_path in file_paths]
labels_df = pd.read_csv(labels_path)

# Identify the non-NaN columns for each annotator
annotator_columns = []
for df in dfs:
    for col in ['annotator1', 'annotator2', 'annotator3']:
        if df[col].notna().any():
            annotator_columns.append(df[col])
            break

arianna_notes = dfs[1]['note'] if 'note' in dfs[1].columns else None

# Create a new DataFrame with the sentence column and the three annotator columns
action_annotations = pd.DataFrame({
    'sentence': dfs[0]['sentence'],
    'davide': annotator_columns[0],
    'arianna': annotator_columns[1],
    'theodora': annotator_columns[2],
    'arianna_note': arianna_notes
})

# Function to compute majority vote
def majority_vote(row):
    return row.mode().iloc[0] if not row.mode().empty else None

# Apply majority vote function
action_annotations['majority'] = action_annotations[['davide', 'arianna', 'theodora']].apply(majority_vote, axis=1)
action_annotations['majority'] = action_annotations['majority'].astype(int)

# Directly copy the 'collectiveAction' column from labels_df to action_annotations
action_annotations['collectiveAction'] = labels_df['collectiveAction']

# Display the result
action_annotations.head()

/var/folders/z_/3vpzgjpj4dv90c8dxq0x3ww80000gn/T/ipykernel_93797/3978836179.py:35: UserWarning: Unable to sort modes: '<' not supported between instances of 'int' and 'str'
  return row.mode().iloc[0] if not row.mode().empty else None

,sentence,davide,arianna,theodora,arianna_note,majority,collectiveAction
0,That's ultimately what it comes out to.,0,0,0,NaN,0,1
1,I think that both those things are wrong.,0,0,0,NaN,0,1
2,"And on average, that food goes from being a waste stream, potentially a waste stream in the store, to instead, by Oleo, one to two hours later, it's been fully redistributed into the homes of the local community.",1,0,1,NaN,1,1
3,It's not like the Exodus story of Egypt where they're all kind of clustered in one place and together.,0,0,0,NaN,0,1
4,"And then you have left, I guess, there's volunteers to actually take care of the whole process of digitizing, but I'm quote the food to put it on the app.",0,0,0,NaN,0,0

In [89]:
action_annotations[['sentence', 'majority']].to_csv('../data/annotation_set_action_majority.csv', index=False)

In [71]:
print(action_annotations[['davide', 'arianna', 'theodora']].dtypes)
print(action_annotations[['davide', 'arianna', 'theodora']].apply(pd.unique))

davide      object
arianna      int64
theodora     int64
dtype: object
davide      [0, 1, ?, nan]
arianna             [0, 1]
theodora            [0, 1]
dtype: object

In [84]:
from sklearn.metrics import accuracy_score, confusion_matrix

action_annotations['collectiveAction'] = 1 - action_annotations['collectiveAction']

# Compute accuracy
accuracy = accuracy_score(action_annotations['collectiveAction'], action_annotations['majority'])

# Compute confusion matrix
tn, fp, fn, tp = confusion_matrix(action_annotations['collectiveAction'], action_annotations['majority']).ravel()

# Print results
print(f'Accuracy: {accuracy:.4f}')
print(f'True Positives (TP): {tp}')
print(f'True Negatives (TN): {tn}')
print(f'False Positives (FP): {fp}')
print(f'False Negatives (FN): {fn}')

Accuracy: 0.6158
True Positives (TP): 24
True Negatives (TN): 93
False Positives (FP): 2
False Negatives (FN): 71

In [73]:
import krippendorff
import numpy as np
import pandas as pd

valid_values = {0, 1}

# Convert all columns to numeric (coerce errors to NaN)
action_annotations[['davide', 'arianna', 'theodora']] = action_annotations[['davide', 'arianna', 'theodora']].apply(pd.to_numeric, errors='coerce')

# Drop rows that contain invalid values (anything other than 0 or 1)
filtered_data = action_annotations.dropna(subset=['davide', 'arianna', 'theodora'])
filtered_data = filtered_data[
    filtered_data[['davide', 'arianna', 'theodora']].applymap(lambda x: x in valid_values).all(axis=1)
]

data = filtered_data[['davide', 'arianna', 'theodora']].to_numpy(dtype=int).T
alpha = krippendorff.alpha(reliability_data=data, level_of_measurement='nominal')
print(f"Krippendorff's alpha: {alpha:.4f}")

Krippendorff's alpha: 0.5463

/var/folders/z_/3vpzgjpj4dv90c8dxq0x3ww80000gn/T/ipykernel_93797/3889767166.py:13: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  filtered_data[['davide', 'arianna', 'theodora']].applymap(lambda x: x in valid_values).all(axis=1)